#!/bin/sh
#
# Perform necessary collectd setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

echo "Stopping collectd service"
[ -x /etc/init.d/collectd ] && /etc/init.d/collectd stop 2>&1 > /dev/null
sleep 10
exit 0
